### PR TITLE
Docker for Windows compatibility

### LINKED ISSUE #80: Working on windows 10 docker integration
I tried to use it on windows 10 but if I do make build powershell gives some errors

`process_begin: CreateProcess(NULL, pwd, ...) failed.
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
make: *** [composer-install] Erreur 1`

I fixed that just changing pwd and making it cross system compliant from $(shell pwd) to ${PWD}

I've removed $(id -u):$(id -g) too since such thing doesn't exist in docker for windows but we could create a volume with those arguments.

Or we could simply have two different make files one for windows and one for linux.

But even if I try to do all the changes to make it works I still getting some errors...
I changed 
`composer-install:
	@docker run --rm --interactive --tty --volume $(shell pwd):/app --user $(id -u):$(id -g) \
		gsingh1/prestissimo install \
			--ignore-platform-reqs \
			--no-ansi \
			--no-interaction`
to
`composer-install:
	@docker run --rm --interactive --tty --volume ${PWD}:/app gsingh1/prestissimo install --ignore-platform-reqs --no-ansi --no-interaction`

Still getting this error:
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Composer could not find a composer.json file in /app
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
make: *** [composer-install] Erreur 1

I don't know why because if I execute the command directly in powershell all seems ok:
`docker run --rm --interactive --tty --volume ${PWD}:/app gsingh1/prestissimo install --ignore-platform-reqs --no-ansi --no-interaction`

Maybe it's related to make but I don't really know much about it...

### PR DESCRIPTION
**Pull request by patrick-mota**
Add compatibility to Docker for Windows and Linux at the same time
Fixes #80

### CODE REVIEW

**Comment by patrick-mota** [comment]
Tested in : 
- Linux
- DnD (via https://labs.play-with-docker.com)
-  Windows 10 (Docker for windows)

**Comment by rgomezcasas** [comment]
Thanks! We'll try with a Windows! (before tomorrow ends) :)

**Comment by patrick-mota** [comment]
No problem, thank you for your fast feedback it's a pleasure to contribute when we get a fast answer 😄

**Comment by rgomezcasas** [comment]
Sorry for the delay! We'll try it today!

**Comment by rgomezcasas** [comment]
Works like a charm! Thanks 🙂

**Comment by bareser** [comment]
Hello, I have windows 10 home, I have installed Docker Toolbox and I have run the make build command.
It has started to download packages but in the end it shows me this error:

$ make build
Unable to find image 'clevyr/prestissimo:latest' locally
latest: Pulling from clevyr/prestissimo
aad63a933944: Pull complete                                                                                             b61c449d5d91: Pull complete                                                                                             3fde16e1397a: Pull complete                                                                                             b1096698ab2a: Pull complete                                                                                             e8dc88fe9f8a: Pull complete                                                                                             f35615996f60: Pull complete                                                                                             97f4e139977b: Pull complete                                                                                             649bec891de8: Pull complete                                                                                             af6bcad316b1: Pull complete                                                                                             e2ada3326131: Pull complete                                                                                             81688d4a328f: Pull complete                                                                                             447b1083cc14: Pull complete                                                                                             3da2115fa6d3: Pull complete                                                                                             41732dd0e67d: Pull complete                                                                                             b0cdc13664f2: Pull complete                                                                                             99887356f7cb: Pull complete                                                                                             Digest: sha256:df1b9ae00bea8ca2485c5b8649842501b52ed9057a9c95c29ab68d4f9d40f3c8
Status: Downloaded newer image for clevyr/prestissimo:latest
**docker: Error response from daemon: invalid mode: /app.
See 'docker run --help'.
make: *** [Makefile:13: composer-install] Error 125**

What can I do?

**Pull request merged**
